import json
from pathlib import Path

import pytest
from browser_parity import render_fixture

import chess_ml_coach.engine as engine_module

FIXTURE = Path(__file__).parent / "fixtures" / "browser_parity.json"


@pytest.fixture(scope="module")
def generated() -> str:
    patcher = pytest.MonkeyPatch()

    def no_live_engine(*_args, **_kwargs):
        raise AssertionError("parity fixture generation must not launch Stockfish")

    patcher.setattr(engine_module, "StockfishAdapter", no_live_engine)
    try:
        return render_fixture()
    finally:
        patcher.undo()


def test_python_pipeline_still_emits_the_committed_parity_fixture(generated):
    assert generated == FIXTURE.read_text(encoding="utf-8"), (
        "Python pipeline output changed; regenerate with "
        "`.venv/bin/python tests/browser_parity.py > tests/fixtures/browser_parity.json` "
        "and update the TypeScript port to match"
    )


def test_fixture_is_canonical_and_free_of_timestamps_and_paths(generated):
    assert json.loads(generated)["description"].startswith("Generated by")
    text = generated.lower()
    assert "/tmp" not in text and "/users/" not in text and "\\\\" not in text
    assert "created_at" not in text and "updated_at" not in text
    assert "t00:00:00" not in text


def test_fixture_exercises_every_classification_and_mate_path(generated):
    document = json.loads(generated)
    qualities = {row["quality"] for row in document["analysis"]}
    reasons = {row["quality_reason"] for row in document["analysis"]}
    assert qualities == {"brilliant", "best", "excellent", "good", "inaccuracy", "mistake",
                         "blunder", "miss"}
    assert {"allows forced mate", "forced mate was available", "delivers checkmate"} <= reasons
    assert {"missed mate", "winning capture", "pin", "forcing check"} <= {
        puzzle["motif"] for puzzle in document["puzzles"]
    }
    assert document["model_summary"]["status"] == "trained"
    assert document["report"]["overall"]["mate_blunders"] > 0
    assert any(key.endswith("|2") for key in document["engine"])
