// Curated opening curriculum. Every line starts from the initial position and
// is validated move-by-move against chess.js in lessons.test.ts, so a typo in a
// SAN string fails CI instead of breaking a drill.

export type Side = 'white' | 'black'

export type LessonMove = {
  san: string
  // One-line reason for the move. Shown after it is played in Learn mode and
  // after a correct answer in Drill mode.
  why: string
}

export type OpeningLesson = {
  id: string
  name: string
  eco: string
  kind: 'line' | 'trap'
  side: Side
  summary: string
  plan: string
  moves: LessonMove[]
}

export type OpeningFamily = {
  id: string
  name: string
  tier: number
  // Lower-case fragments matched against Chess.com opening labels to recommend
  // families where the player's own games produce the most mistakes.
  keywords: string[]
  lessons: OpeningLesson[]
}

export type Tier = { id: number; title: string; blurb: string }

const m = (san: string, why: string): LessonMove => ({ san, why })

export const TIERS: Tier[] = [
  { id: 0, title: 'Principles', blurb: 'Center, development, king safety — the ideas every opening below is built on.' },
  { id: 1, title: 'Open games', blurb: '1.e4 e5: sharp, classical positions where the principles pay off fastest.' },
  { id: 2, title: 'Semi-open games', blurb: 'Black meets 1.e4 with anything but 1…e5 and fights for the center asymmetrically.' },
  { id: 3, title: 'Closed games', blurb: '1.d4 structures: slower maneuvering, pawn chains, and long-term plans.' },
  { id: 4, title: 'Flank openings', blurb: 'Control the center from the side before occupying it.' },
]

export const FAMILIES: OpeningFamily[] = [
  {
    id: 'principles',
    name: 'Opening principles',
    tier: 0,
    keywords: ["king's pawn", 'kings pawn', 'scholar', 'wayward queen', 'bishops opening', "bishop's opening"],
    lessons: [
      {
        id: 'principles-classical-setup',
        name: 'The classical setup',
        eco: 'C50',
        kind: 'line',
        side: 'white',
        summary: 'A calm Italian setup that shows every opening principle in eight moves.',
        plan: 'Pieces out before pawns, castle early, and only then start pushing pawns to fight for space.',
        moves: [
          m('e4', 'Grabs central space and opens lines for the queen and the light-squared bishop.'),
          m('e5', 'Black claims an equal share of the center.'),
          m('Nf3', 'Develops toward the center with tempo — the e5 pawn is attacked.'),
          m('Nc6', 'Defends e5 while developing. Knights before bishops.'),
          m('Bc4', 'The bishop takes its most active diagonal and eyes f7, the weakest square near the black king.'),
          m('Bc5', 'Black mirrors the idea and aims at f2.'),
          m('O-O', 'King safety first: castling tucks the king away and connects the rook to the center.'),
          m('Nf6', 'Develops the last minor piece toward the center and attacks e4.'),
          m('d3', 'A modest pawn move that defends e4 and opens the c1 bishop.'),
          m('d6', 'Same idea for Black: solid center, open diagonal for the c8 bishop.'),
        ],
      },
      {
        id: 'trap-scholars-mate-defense',
        name: "Stopping Scholar's Mate",
        eco: 'C20',
        kind: 'trap',
        side: 'black',
        summary: 'The most common beginner attack: queen and bishop gang up on f7. Learn the calm, developing refutation.',
        plan: 'Block the queen with a pawn, then develop with tempo. An early queen becomes a target for your pieces.',
        moves: [
          m('e4', 'White opens the queen and bishop.'),
          m('e5', 'Claim the center.'),
          m('Qh5', 'An early queen sortie, hitting e5 and eyeing f7.'),
          m('Nc6', 'Defend e5 by developing a piece — never with a passive pawn move.'),
          m('Bc4', 'Now Qxf7 is mate, so the threat must be addressed.'),
          m('g6', 'Blocks the queen and gains time: the queen must move again.'),
          m('Qf3', 'White renews the threat on f7.'),
          m('Nf6', 'Blocks the f-file with a developing move. Black is ahead in development and the white queen is misplaced.'),
        ],
      },
    ],
  },
  {
    id: 'italian',
    name: 'Italian Game',
    tier: 1,
    keywords: ['italian', 'giuoco', 'two knights', 'evans', 'fried liver'],
    lessons: [
      {
        id: 'italian-giuoco-pianissimo',
        name: 'Giuoco Pianissimo',
        eco: 'C53',
        kind: 'line',
        side: 'white',
        summary: 'The modern, slow Italian: prepare d4 with c3 and d3 and keep a flexible center.',
        plan: 'Play a4, Re1, Nbd2-f1-g3 and only then consider d4. Patience wins over early fireworks.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Develop with tempo on e5.'),
          m('Nc6', 'Defends and develops.'),
          m('Bc4', 'The Italian bishop: pressure on f7.'),
          m('Bc5', 'Black mirrors and hits f2.'),
          m('c3', 'Prepares d4 and gives the c5 bishop a future target.'),
          m('Nf6', 'Develops and attacks e4.'),
          m('d3', 'Defends e4 solidly and keeps the tension for later.'),
          m('d6', 'Black does the same.'),
          m('O-O', 'King safe before any middlegame plan.'),
          m('O-O', 'Both sides are fully mobilized.'),
        ],
      },
      {
        id: 'italian-giuoco-piano',
        name: 'Giuoco Piano: main line',
        eco: 'C54',
        kind: 'line',
        side: 'white',
        summary: 'The direct plan: c3 and d4 at once to build a big pawn center.',
        plan: 'Use the open e-file and your central pawn to attack; recapture on d2 with a knight to keep the center strong.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Develop with tempo.'),
          m('Nc6', 'Defends e5.'),
          m('Bc4', 'Aim at f7.'),
          m('Bc5', 'Aim at f2.'),
          m('c3', 'Prepares an immediate d4.'),
          m('Nf6', 'Counterattacks e4.'),
          m('d4', 'Strikes in the center with tempo on the c5 bishop.'),
          m('exd4', 'Black releases the tension.'),
          m('cxd4', 'Two pawns side by side in the center.'),
          m('Bb4+', 'The only good square for the bishop, with check.'),
          m('Bd2', 'Blocks and offers a trade of dark-squared bishops.'),
          m('Bxd2+', 'Black trades.'),
          m('Nbxd2', 'Recapture with the knight so d4 stays defended.'),
          m('d5', 'Black strikes back at the center — the key freeing move.'),
          m('exd5', 'Opens the e-file.'),
          m('Nxd5', 'Black’s knight lands on a strong central square.'),
        ],
      },
      {
        id: 'italian-evans-gambit',
        name: 'Evans Gambit',
        eco: 'C52',
        kind: 'line',
        side: 'white',
        summary: 'Give a pawn to gain several tempi and a huge center.',
        plan: 'Castle fast, play d4, and throw pieces at the black king before Black can consolidate the extra pawn.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Develop with tempo.'),
          m('Nc6', 'Defends e5.'),
          m('Bc4', 'Aim at f7.'),
          m('Bc5', 'Aim at f2.'),
          m('b4', 'The gambit: deflect the bishop and gain time for c3 and d4.'),
          m('Bxb4', 'Black accepts the pawn.'),
          m('c3', 'Hits the bishop again and prepares d4.'),
          m('Ba5', 'Keeps the pin idea on c3.'),
          m('d4', 'Builds the center with tempo against e5.'),
          m('exd4', 'Black grabs more material.'),
          m('O-O', 'King safe, rook ready for e1. White is far ahead in development.'),
        ],
      },
      {
        id: 'italian-two-knights',
        name: 'Two Knights Defense',
        eco: 'C59',
        kind: 'line',
        side: 'black',
        summary: 'Black counterattacks e4 instead of copying White and meets Ng5 with a pawn sacrifice for activity.',
        plan: 'Chase White’s pieces with ...e4 and ...Bd6, develop quickly, and use the half-open lines for the pawn.',
        moves: [
          m('e4', 'White opens.'),
          m('e5', 'Claim the center.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defend by developing.'),
          m('Bc4', 'The Italian bishop.'),
          m('Nf6', 'Counterattack e4 instead of copying White.'),
          m('Ng5', 'White attacks f7 a second time.'),
          m('d5', 'Block the bishop — the only good defense.'),
          m('exd5', 'White wins the pawn.'),
          m('Na5', 'Hit the bishop. Do not recapture on d5 — that allows the Fried Liver.'),
          m('Bb5+', 'The bishop leaves with check.'),
          m('c6', 'Block with tempo.'),
          m('dxc6', 'White keeps the extra pawn.'),
          m('bxc6', 'Open the b-file and develop toward the center.'),
          m('Be2', 'Retreat.'),
          m('h6', 'Kick the knight and gain more time.'),
          m('Nf3', 'Retreat.'),
          m('e4', 'Chase the knight a third time.'),
          m('Ne5', 'Centralize.'),
          m('Bd6', 'Develop and challenge e5: full compensation for the pawn.'),
        ],
      },
      {
        id: 'trap-fried-liver',
        name: 'Fried Liver Attack',
        eco: 'C57',
        kind: 'trap',
        side: 'white',
        summary: 'Punish 5…Nxd5?! with a knight sacrifice on f7 that drags the black king into the open.',
        plan: 'Keep adding attackers to the pinned d5 knight: Nc3, d4, O-O, Re1. The king has nowhere safe to hide.',
        moves: [
          m('e4', 'Open.'),
          m('e5', 'Black mirrors.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defends.'),
          m('Bc4', 'Target f7.'),
          m('Nf6', 'Two Knights Defense.'),
          m('Ng5', 'Double attack on f7.'),
          m('d5', 'Correct block.'),
          m('exd5', 'Win the pawn.'),
          m('Nxd5', 'Natural, but it allows the sacrifice.'),
          m('Nxf7', 'The Fried Liver: rip open the king.'),
          m('Kxf7', 'Black accepts.'),
          m('Qf3+', 'Fork the king and the d5 knight.'),
          m('Ke6', 'The only way to keep the knight.'),
          m('Nc3', 'Add a third attacker to d5. The black king is stuck in the middle of the board.'),
        ],
      },
    ],
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy Lopez',
    tier: 1,
    keywords: ['ruy lopez', 'spanish', 'berlin', 'morphy', 'noah'],
    lessons: [
      {
        id: 'ruy-exchange',
        name: 'Exchange Variation',
        eco: 'C69',
        kind: 'line',
        side: 'white',
        summary: 'Give up the bishop pair for a healthier pawn structure and aim for good endgames.',
        plan: 'Trade pieces. White’s 4-vs-3 kingside majority can make a passed pawn; Black’s doubled c-pawns cannot.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defends e5.'),
          m('Bb5', 'The Spanish bishop pressures the defender of e5.'),
          m('a6', 'Question the bishop at once.'),
          m('Bxc6', 'Exchange: damage Black’s structure.'),
          m('dxc6', 'Capture toward the center and open the c8 bishop.'),
          m('O-O', 'Castle; Nxe5 is not a threat yet, because ...Qd4 would win the pawn back.'),
          m('f6', 'Solid defense of e5.'),
          m('d4', 'Open the center while Black’s king is still uncastled.'),
          m('exd4', 'Black trades.'),
          m('Nxd4', 'Centralize.'),
          m('c5', 'Kick the knight.'),
          m('Nb3', 'Retreat; the queen trade that follows suits White’s endgame plan.'),
        ],
      },
      {
        id: 'ruy-closed',
        name: 'Closed Ruy Lopez',
        eco: 'C84',
        kind: 'line',
        side: 'white',
        summary: 'The main line of the oldest grandmaster opening: slow pressure on e5.',
        plan: 'h3, d4, and the long Nbd2-f1-g3 maneuver. The b3 bishop points at f7 for the whole game.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defends.'),
          m('Bb5', 'Pressure the e5 defender.'),
          m('a6', 'Morphy Defense.'),
          m('Ba4', 'Keep the pin idea alive.'),
          m('Nf6', 'Develop and hit e4.'),
          m('O-O', 'e4 is indirectly defended thanks to Re1 ideas.'),
          m('Be7', 'Closed variation: calm development.'),
          m('Re1', 'Defend e4 for real.'),
          m('b5', 'Now Bxc6 then Nxe5 was threatened.'),
          m('Bb3', 'The bishop’s best diagonal.'),
          m('d6', 'Support e5 and open the c8 bishop.'),
          m('c3', 'Prepare d4 and give the bishop a retreat on c2.'),
          m('O-O', 'Black is safe.'),
          m('h3', 'Stop ...Bg4 before playing d4.'),
        ],
      },
      {
        id: 'ruy-berlin',
        name: 'Berlin Defense',
        eco: 'C67',
        kind: 'line',
        side: 'black',
        summary: 'The Berlin Wall: trade queens early and reach a rock-solid endgame with the bishop pair.',
        plan: 'Play ...h6, ...Ke8 or ...Kc8, and ...Be7. The bishops and the solid structure hold everything.',
        moves: [
          m('e4', 'White opens.'),
          m('e5', 'Claim the center.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defend.'),
          m('Bb5', 'The Spanish.'),
          m('Nf6', 'The Berlin: counterattack e4 at once.'),
          m('O-O', 'White offers e4.'),
          m('Nxe4', 'Take it — White regains it, but the trades suit Black.'),
          m('d4', 'Open the e-file toward the black king.'),
          m('Nd6', 'Hit the bishop and block the d-file.'),
          m('Bxc6', 'White gives up the bishop.'),
          m('dxc6', 'Capture toward the center and open the diagonals.'),
          m('dxe5', 'White regains the pawn with tempo.'),
          m('Nf5', 'The only good square.'),
          m('Qxd8+', 'Queens come off.'),
          m('Kxd8', 'Black loses castling, but with the queens gone the king is safe.'),
        ],
      },
      {
        id: 'trap-noahs-ark',
        name: "Noah's Ark Trap",
        eco: 'C71',
        kind: 'trap',
        side: 'black',
        summary: 'Trap the Spanish bishop on b3 with a pawn chain when White grabs a pawn with the queen.',
        plan: 'After 8.Qxd4?? play ...c5 and ...c4. The queen cannot protect the bishop forever.',
        moves: [
          m('e4', 'White opens.'),
          m('e5', 'Center.'),
          m('Nf3', 'Tempo.'),
          m('Nc6', 'Defend.'),
          m('Bb5', 'The Spanish.'),
          m('a6', 'Question the bishop.'),
          m('Ba4', 'Retreat.'),
          m('d6', 'Steinitz Deferred: solid e5.'),
          m('d4', 'White challenges the center.'),
          m('b5', 'Gain space with tempo.'),
          m('Bb3', 'Retreat.'),
          m('Nxd4', 'Removes the defender of d4…'),
          m('Nxd4', 'White recaptures.'),
          m('exd4', '…and the d4 pawn is now bait.'),
          m('Qxd4', 'The mistake: grabbing the pawn.'),
          m('c5', 'Hit the queen and start building the ark.'),
          m('Qd5', 'The queen tries to stay active.'),
          m('Be6', 'Block the diagonal with tempo.'),
          m('Qc6+', 'A spite check.'),
          m('Bd7', 'Block again.'),
          m('Qd5', 'Back again.'),
          m('c4', 'The bishop on b3 is trapped. Black wins a piece.'),
        ],
      },
    ],
  },
  {
    id: 'scotch-petrov',
    name: 'Scotch & Petrov',
    tier: 1,
    keywords: ['scotch', 'petrov', 'petroff', 'russian game'],
    lessons: [
      {
        id: 'scotch-mieses',
        name: 'Scotch Game: Mieses',
        eco: 'C45',
        kind: 'line',
        side: 'white',
        summary: 'Open the center immediately with 3.d4 and gain space with e5.',
        plan: 'Use the e5 space to cramp Black, then play c4 to kick the d5 knight and put pressure on the queenside.',
        moves: [
          m('e4', 'Central space.'),
          m('e5', 'Black stakes a claim.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nc6', 'Defends.'),
          m('d4', 'The Scotch: open the center right away.'),
          m('exd4', 'Black takes.'),
          m('Nxd4', 'Recapture with a centralized knight.'),
          m('Nf6', 'Develop and hit e4.'),
          m('Nxc6', 'Trade to weaken Black’s structure.'),
          m('bxc6', 'Recapture toward the center.'),
          m('e5', 'Gain space with tempo on f6.'),
          m('Qe7', 'Pin the e5 pawn.'),
          m('Qe2', 'Unpin.'),
          m('Nd5', 'The knight finds a central square.'),
          m('c4', 'Kick it.'),
        ],
      },
      {
        id: 'petrov-classical',
        name: "Petrov's Defense",
        eco: 'C42',
        kind: 'line',
        side: 'black',
        summary: 'Counterattack e4 instead of defending e5. Solid and symmetrical.',
        plan: 'Keep the e4 knight well supported with ...d5, ...Bd6 and ...O-O; equal but hard to crack.',
        moves: [
          m('e4', 'White opens.'),
          m('e5', 'Center.'),
          m('Nf3', 'Tempo on e5.'),
          m('Nf6', 'The Petrov: counterattack.'),
          m('Nxe5', 'White takes first.'),
          m('d6', 'Kick the knight BEFORE taking back — order matters.'),
          m('Nf3', 'Retreat.'),
          m('Nxe4', 'Now regain the pawn safely.'),
          m('d4', 'White takes the center.'),
          m('d5', 'Support the knight.'),
          m('Bd3', 'Develop and challenge e4.'),
        ],
      },
      {
        id: 'trap-petrov-nc6',
        name: 'Petrov trap: 5.Nc6+',
        eco: 'C42',
        kind: 'trap',
        side: 'white',
        summary: 'If Black copies White with 3…Nxe4?, the e-file opens and a discovered check wins the queen.',
        plan: 'After 3…Nxe4, 4.Qe2 is the key move. If Black misses it, the knight uncovers check and hits d8.',
        moves: [
          m('e4', 'Open.'),
          m('e5', 'Center.'),
          m('Nf3', 'Tempo.'),
          m('Nf6', 'Petrov.'),
          m('Nxe5', 'Take first.'),
          m('Nxe4', 'The mistake: copying White.'),
          m('Qe2', 'Pin down the e-file: the knight on e4 is attacked.'),
          m('Nf6', 'The blunder. 4…Qe7 was necessary.'),
          m('Nc6+', 'Discovered check from the queen, and the knight hits the queen on d8.'),
        ],
      },
    ],
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian Defense',
    tier: 2,
    keywords: ['scandinavian', 'center counter'],
    lessons: [
      {
        id: 'scandinavian-main',
        name: 'Scandinavian: …Qa5',
        eco: 'B01',
        kind: 'line',
        side: 'black',
        summary: 'Challenge e4 immediately. The queen comes out early but finds a safe, active square.',
        plan: 'The Caro-Kann-like setup ...c6, ...Bf5, ...e6: solid pawns, active light-squared bishop.',
        moves: [
          m('e4', 'White opens.'),
          m('d5', 'Challenge e4 on move one.'),
          m('exd5', 'White takes.'),
          m('Qxd5', 'Recapture — the queen is out, but safe for now.'),
          m('Nc3', 'White develops with tempo.'),
          m('Qa5', 'Safe and active: pins c3 if d4 ever loosens.'),
          m('d4', 'Central space.'),
          m('Nf6', 'Develop.'),
          m('Nf3', 'Develop.'),
          m('c6', 'Give the queen a retreat to c7 and control d5/b5.'),
          m('Bc4', 'Develop.'),
          m('Bf5', 'Bring the bishop out before playing ...e6.'),
        ],
      },
    ],
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defense',
    tier: 2,
    keywords: ['caro kann', 'caro-kann'],
    lessons: [
      {
        id: 'caro-classical',
        name: 'Classical Variation',
        eco: 'B19',
        kind: 'line',
        side: 'black',
        summary: 'Solid central pawns and an active light-squared bishop outside the pawn chain.',
        plan: 'Finish with ...e6, ...Ngf6, ...Be7 and ...O-O or ...O-O-O. Few weaknesses, easy development.',
        moves: [
          m('e4', 'White opens.'),
          m('c6', 'Prepare ...d5 while keeping the c8 bishop free.'),
          m('d4', 'White takes the full center.'),
          m('d5', 'Challenge e4.'),
          m('Nc3', 'Defend e4.'),
          m('dxe4', 'Release the tension.'),
          m('Nxe4', 'Recapture.'),
          m('Bf5', 'Develop the bishop outside the chain with tempo.'),
          m('Ng3', 'Kick it.'),
          m('Bg6', 'Keep the diagonal.'),
          m('h4', 'Threaten h5 to trap the bishop.'),
          m('h6', 'Give the bishop a retreat square.'),
          m('Nf3', 'Develop.'),
          m('Nd7', 'Stop Ne5 and prepare ...Ngf6.'),
          m('h5', 'Gain space.'),
          m('Bh7', 'The bishop still controls the long diagonal.'),
        ],
      },
      {
        id: 'caro-advance',
        name: 'Advance Variation',
        eco: 'B12',
        kind: 'line',
        side: 'black',
        summary: 'White gains space with e5; Black develops the bishop, then hits the chain with ...c5.',
        plan: 'Attack the base of White’s chain (d4) with ...c5 and ...Nc6; do not lock your bishop in with ...e6 first.',
        moves: [
          m('e4', 'White opens.'),
          m('c6', 'Caro-Kann.'),
          m('d4', 'Center.'),
          m('d5', 'Challenge.'),
          m('e5', 'White gains space.'),
          m('Bf5', 'Bishop out BEFORE ...e6.'),
          m('Nf3', 'Develop.'),
          m('e6', 'Now it is safe to close the diagonal behind the bishop.'),
          m('Be2', 'Develop.'),
          m('c5', 'Hit the base of the pawn chain.'),
          m('O-O', 'White castles.'),
          m('Nc6', 'Add pressure on d4.'),
          m('c3', 'White supports d4.'),
        ],
      },
    ],
  },
  {
    id: 'french',
    name: 'French Defense',
    tier: 2,
    keywords: ['french'],
    lessons: [
      {
        id: 'french-exchange',
        name: 'Exchange Variation',
        eco: 'C01',
        kind: 'line',
        side: 'black',
        summary: 'A symmetrical structure. Easy development and equal chances.',
        plan: 'Mirror White’s development, castle, and fight for the open e-file.',
        moves: [
          m('e4', 'White opens.'),
          m('e6', 'Prepare ...d5 with pawn support.'),
          m('d4', 'Center.'),
          m('d5', 'Challenge.'),
          m('exd5', 'Exchange.'),
          m('exd5', 'Symmetry; the c8 bishop is now free.'),
          m('Nf3', 'Develop.'),
          m('Nf6', 'Develop.'),
          m('Bd3', 'Develop.'),
          m('Bd6', 'Develop.'),
          m('O-O', 'Castle.'),
          m('O-O', 'Castle.'),
        ],
      },
      {
        id: 'french-advance',
        name: 'Advance Variation',
        eco: 'C02',
        kind: 'line',
        side: 'black',
        summary: 'White builds a big chain; Black attacks its base on d4 with every piece.',
        plan: 'Pressure d4 with ...c5, ...Nc6, ...Qb6 and ...Nge7-f5. Close the queenside with ...c4 when a3/b4 appear.',
        moves: [
          m('e4', 'White opens.'),
          m('e6', 'French.'),
          m('d4', 'Center.'),
          m('d5', 'Challenge.'),
          m('e5', 'Advance: space.'),
          m('c5', 'Strike the base of the chain immediately.'),
          m('c3', 'Support d4.'),
          m('Nc6', 'Pressure d4.'),
          m('Nf3', 'Support d4.'),
          m('Qb6', 'A third attacker on d4, also eyeing b2.'),
          m('a3', 'White prepares b4.'),
          m('c4', 'Lock the queenside so b4 cannot open lines.'),
        ],
      },
      {
        id: 'french-winawer',
        name: 'Winawer Variation',
        eco: 'C18',
        kind: 'line',
        side: 'black',
        summary: 'Pin the c3 knight, give up the bishop, and wreck White’s pawn structure.',
        plan: 'Target the doubled c-pawns with ...Qa5 and ...Nbc6; keep the position closed so White’s bishops stay passive.',
        moves: [
          m('e4', 'White opens.'),
          m('e6', 'French.'),
          m('d4', 'Center.'),
          m('d5', 'Challenge.'),
          m('Nc3', 'Defend e4.'),
          m('Bb4', 'The Winawer: pin the defender of e4.'),
          m('e5', 'White gains space.'),
          m('c5', 'Hit the chain.'),
          m('a3', 'Question the bishop.'),
          m('Bxc3+', 'Give up the bishop for structure.'),
          m('bxc3', 'Doubled c-pawns for White.'),
          m('Ne7', 'Develop toward f5 or c6; avoid blocking the f-pawn.'),
        ],
      },
    ],
  },
  {
    id: 'sicilian',
    name: 'Sicilian Defense',
    tier: 2,
    keywords: ['sicilian'],
    lessons: [
      {
        id: 'sicilian-alapin',
        name: 'Alapin Variation',
        eco: 'B22',
        kind: 'line',
        side: 'white',
        summary: 'A simple anti-Sicilian for White: prepare d4 with c3 so you can recapture with a pawn.',
        plan: 'A classical center with pieces on natural squares: Bc4 or Bd3, O-O, Nc3.',
        moves: [
          m('e4', 'Open.'),
          m('c5', 'The Sicilian fights for d4 from the side.'),
          m('c3', 'Prepare d4 and recapture with a pawn.'),
          m('Nf6', 'Hit e4 at once.'),
          m('e5', 'Gain space with tempo.'),
          m('Nd5', 'Central knight.'),
          m('d4', 'Build the center.'),
          m('cxd4', 'Black takes.'),
          m('Nf3', 'Develop first; the pawn is not going anywhere.'),
          m('Nc6', 'Develop.'),
          m('cxd4', 'Recapture: a strong pawn duo on d4 and e5.'),
          m('d6', 'Black challenges e5.'),
        ],
      },
      {
        id: 'sicilian-najdorf',
        name: 'Najdorf Variation',
        eco: 'B90',
        kind: 'line',
        side: 'black',
        summary: 'The most famous Sicilian: ...a6 controls b5 and keeps every option open.',
        plan: 'Against 6.Be3, play ...e5 to kick the d4 knight and then ...Be6, ...Nbd7, ...b5 on the queenside.',
        moves: [
          m('e4', 'White opens.'),
          m('c5', 'Sicilian.'),
          m('Nf3', 'Prepare d4.'),
          m('d6', 'Control e5 and open the c8 bishop.'),
          m('d4', 'Open Sicilian.'),
          m('cxd4', 'Trade a flank pawn for a center pawn.'),
          m('Nxd4', 'Recapture.'),
          m('Nf6', 'Develop and hit e4.'),
          m('Nc3', 'Defend.'),
          m('a6', 'The Najdorf: control b5 and prepare ...e5 or ...b5.'),
          m('Be3', 'English Attack setup.'),
          m('e5', 'Kick the knight and grab central space.'),
          m('Nb3', 'Retreat.'),
          m('Be6', 'Control d5, the key square.'),
        ],
      },
      {
        id: 'sicilian-dragon',
        name: 'Dragon Variation',
        eco: 'B76',
        kind: 'line',
        side: 'black',
        summary: 'Fianchetto on g7 aims straight down the long diagonal at White’s queenside.',
        plan: 'Race White’s attack: ...Nc6, ...d5 or ...Bd7, ...Rc8 and a sacrifice on c3 are typical.',
        moves: [
          m('e4', 'White opens.'),
          m('c5', 'Sicilian.'),
          m('Nf3', 'Prepare d4.'),
          m('d6', 'Control e5.'),
          m('d4', 'Open Sicilian.'),
          m('cxd4', 'Trade.'),
          m('Nxd4', 'Recapture.'),
          m('Nf6', 'Hit e4.'),
          m('Nc3', 'Defend.'),
          m('g6', 'The Dragon: prepare ...Bg7.'),
          m('Be3', 'Yugoslav Attack setup.'),
          m('Bg7', 'The dragon bishop.'),
          m('f3', 'Stop ...Ng4 and prepare g4.'),
          m('O-O', 'Castle.'),
          m('Qd2', 'Prepare Bh6 and O-O-O.'),
          m('Nc6', 'Develop and pressure d4.'),
        ],
      },
      {
        id: 'sicilian-classical',
        name: 'Classical Variation',
        eco: 'B62',
        kind: 'line',
        side: 'black',
        summary: 'Develop naturally with ...Nc6 and meet the Richter-Rauzer with ...e6 and ...a6.',
        plan: 'Queenside expansion with ...a6, ...Bd7, ...b5 while White castles long.',
        moves: [
          m('e4', 'White opens.'),
          m('c5', 'Sicilian.'),
          m('Nf3', 'Prepare d4.'),
          m('d6', 'Control e5.'),
          m('d4', 'Open Sicilian.'),
          m('cxd4', 'Trade.'),
          m('Nxd4', 'Recapture.'),
          m('Nf6', 'Hit e4.'),
          m('Nc3', 'Defend.'),
          m('Nc6', 'Classical: develop naturally.'),
          m('Bg5', 'Richter-Rauzer: pin and discourage ...g6.'),
          m('e6', 'Solid: support d5 and open the f8 bishop.'),
          m('Qd2', 'Prepare long castling.'),
          m('a6', 'Control b5 and prepare ...b5.'),
        ],
      },
    ],
  },
  {
    id: 'london',
    name: 'London System',
    tier: 3,
    keywords: ['london'],
    lessons: [
      {
        id: 'london-main',
        name: 'London System',
        eco: 'D02',
        kind: 'line',
        side: 'white',
        summary: 'The same setup against almost anything: Bf4, e3, c3, Nf3, Nbd2, Bd3.',
        plan: 'A pyramid of pawns on c3–d4–e3; later Ne5 and a kingside attack.',
        moves: [
          m('d4', 'Central space; the pawn is already defended by the queen.'),
          m('d5', 'Black matches.'),
          m('Bf4', 'Develop the bishop before e3 locks it in.'),
          m('Nf6', 'Develop.'),
          m('e3', 'Support d4 and open the f1 bishop.'),
          m('e6', 'Black is solid.'),
          m('Nf3', 'Develop.'),
          m('c5', 'Black challenges d4.'),
          m('c3', 'Complete the pyramid.'),
          m('Nc6', 'More pressure.'),
          m('Nbd2', 'Develop without blocking c3.'),
          m('Bd6', 'Challenge the f4 bishop.'),
          m('Bg3', 'Keep the bishop; a trade on g3 would open the h-file for White.'),
          m('O-O', 'Castle.'),
          m('Bd3', 'Aim at h7.'),
        ],
      },
    ],
  },
  {
    id: 'queens-gambit',
    name: "Queen's Gambit",
    tier: 3,
    keywords: ["queen's gambit", 'queens gambit', 'slav', 'semi slav'],
    lessons: [
      {
        id: 'qga-main',
        name: "Queen's Gambit Accepted",
        eco: 'D27',
        kind: 'line',
        side: 'white',
        summary: 'Black takes c4 but cannot hold it; White regains it with a lead in development.',
        plan: 'Recover the pawn with Bxc4, castle, and play for e4 or a kingside initiative.',
        moves: [
          m('d4', 'Center.'),
          m('d5', 'Black matches.'),
          m('c4', 'The gambit: trade a flank pawn for a center pawn.'),
          m('dxc4', 'Black accepts.'),
          m('Nf3', 'Stop ...e5 before regaining the pawn.'),
          m('Nf6', 'Develop.'),
          m('e3', 'Open the bishop toward c4.'),
          m('e6', 'Solid.'),
          m('Bxc4', 'Pawn regained with a tempo.'),
          m('c5', 'Black challenges d4.'),
          m('O-O', 'Castle.'),
          m('a6', 'Prepare ...b5.'),
        ],
      },
      {
        id: 'qgd-tartakower',
        name: "Queen's Gambit Declined",
        eco: 'D58',
        kind: 'line',
        side: 'black',
        summary: 'Hold d5 with ...e6 and develop solidly; the Tartakower setup solves the c8 bishop.',
        plan: '...Bb7 and ...c5 to free the position. Patience: the solidity comes first.',
        moves: [
          m('d4', 'White opens.'),
          m('d5', 'Center.'),
          m('c4', 'The gambit.'),
          m('e6', 'Decline: keep a pawn on d5.'),
          m('Nc3', 'Pressure d5.'),
          m('Nf6', 'Defend d5.'),
          m('Bg5', 'Pin the defender.'),
          m('Be7', 'Break the pin.'),
          m('e3', 'Develop.'),
          m('O-O', 'Castle.'),
          m('Nf3', 'Develop.'),
          m('h6', 'Ask the bishop.'),
          m('Bh4', 'Keep the pin.'),
          m('b6', 'Tartakower: the c8 bishop goes to b7.'),
        ],
      },
      {
        id: 'trap-elephant',
        name: 'Elephant Trap',
        eco: 'D51',
        kind: 'trap',
        side: 'black',
        summary: 'The pin on f6 is fake: if White grabs d5, Black wins a piece with a check on b4.',
        plan: 'After 6.Nxd5?? recapture and let White take the queen; ...Bb4+ wins it back and more.',
        moves: [
          m('d4', 'White opens.'),
          m('d5', 'Center.'),
          m('c4', 'Gambit.'),
          m('e6', 'Decline.'),
          m('Nc3', 'Pressure d5.'),
          m('Nf6', 'Defend.'),
          m('Bg5', 'Pin.'),
          m('Nbd7', 'The bait: d5 looks loose.'),
          m('cxd5', 'Exchange.'),
          m('exd5', 'Recapture.'),
          m('Nxd5', 'The mistake: the f6 knight only seems pinned.'),
          m('Nxd5', 'Give up the queen!'),
          m('Bxd8', 'White takes it.'),
          m('Bb4+', 'Check — White must give the queen back.'),
          m('Qd2', 'Forced block.'),
          m('Bxd2+', 'Take it.'),
          m('Kxd2', 'Recapture.'),
          m('Kxd8', 'Black is a knight up.'),
        ],
      },
      {
        id: 'slav-main',
        name: 'Slav Defense',
        eco: 'D17',
        kind: 'line',
        side: 'black',
        summary: 'Hold d5 with ...c6, keeping the c8 bishop free — unlike the Queen’s Gambit Declined.',
        plan: 'Take c4, develop ...Bf5 and ...e6, then aim ...Bb4 at c3.',
        moves: [
          m('d4', 'White opens.'),
          m('d5', 'Center.'),
          m('c4', 'Gambit.'),
          m('c6', 'The Slav: defend d5 and keep the bishop free.'),
          m('Nf3', 'Develop.'),
          m('Nf6', 'Develop.'),
          m('Nc3', 'Pressure d5.'),
          m('dxc4', 'Now take — White has to work to get it back.'),
          m('a4', 'Stop ...b5.'),
          m('Bf5', 'The point of the Slav: bishop outside the chain.'),
          m('e3', 'Prepare Bxc4.'),
          m('e6', 'Solid.'),
          m('Bxc4', 'Pawn regained.'),
          m('Bb4', 'Pin and pressure c3.'),
        ],
      },
    ],
  },
  {
    id: 'indian',
    name: 'Indian Defenses',
    tier: 3,
    keywords: ['indian', 'nimzo', "king's indian", 'kings indian', "queen's indian", 'queens indian'],
    lessons: [
      {
        id: 'nimzo-indian',
        name: 'Nimzo-Indian Defense',
        eco: 'E46',
        kind: 'line',
        side: 'black',
        summary: 'Pin the c3 knight to fight for e4 with pieces instead of pawns.',
        plan: 'Be ready to give the bishop for the c3 knight to double White’s pawns; strike with ...c5 and ...d5.',
        moves: [
          m('d4', 'White opens.'),
          m('Nf6', 'Control e4 with a piece.'),
          m('c4', 'Space.'),
          m('e6', 'Open the f8 bishop.'),
          m('Nc3', 'Prepare e4.'),
          m('Bb4', 'The Nimzo: pin and stop e4.'),
          m('e3', 'Rubinstein: solid development.'),
          m('O-O', 'Castle.'),
          m('Bd3', 'Develop.'),
          m('d5', 'Stake the center.'),
          m('Nf3', 'Develop.'),
          m('c5', 'Hit d4.'),
          m('O-O', 'Castle.'),
        ],
      },
      {
        id: 'queens-indian',
        name: "Queen's Indian Defense",
        eco: 'E15',
        kind: 'line',
        side: 'black',
        summary: 'When White avoids the Nimzo pin with Nf3, control e4 with a fianchettoed bishop.',
        plan: 'The ...Ba6 trick pressures c4; after ...Be7 and ...O-O Black is compact and solid.',
        moves: [
          m('d4', 'White opens.'),
          m('Nf6', 'Control e4.'),
          m('c4', 'Space.'),
          m('e6', 'Flexible.'),
          m('Nf3', 'Avoid the Nimzo pin.'),
          m('b6', 'Queen’s Indian: fianchetto toward e4.'),
          m('g3', 'White fianchettoes too.'),
          m('Ba6', 'Hit c4 before White can finish development.'),
          m('b3', 'Defend c4.'),
          m('Bb4+', 'Disrupt with check.'),
          m('Bd2', 'Block.'),
          m('Be7', 'Retreat; the d2 bishop now blocks the queen’s defense of d4.'),
        ],
      },
      {
        id: 'kings-indian',
        name: "King's Indian Defense",
        eco: 'E97',
        kind: 'line',
        side: 'black',
        summary: 'Let White build a big center, then attack it and the white king with pawns.',
        plan: 'After d5 closes the center, play ...Ne7, ...Nd7 or ...Ne8, ...f5 and storm the kingside.',
        moves: [
          m('d4', 'White opens.'),
          m('Nf6', 'Control e4.'),
          m('c4', 'Space.'),
          m('g6', 'Prepare the fianchetto.'),
          m('Nc3', 'Prepare e4.'),
          m('Bg7', 'The King’s Indian bishop.'),
          m('e4', 'White takes the full center.'),
          m('d6', 'Prepare ...e5.'),
          m('Nf3', 'Develop.'),
          m('O-O', 'Castle before striking.'),
          m('Be2', 'Develop.'),
          m('e5', 'Strike the center.'),
          m('O-O', 'Castle.'),
          m('Nc6', 'Pressure d4.'),
          m('d5', 'White closes the center.'),
          m('Ne7', 'Reroute toward the kingside for ...f5.'),
        ],
      },
    ],
  },
  {
    id: 'flank',
    name: 'English & Réti',
    tier: 4,
    keywords: ['english', 'reti', 'réti', 'zukertort'],
    lessons: [
      {
        id: 'english-four-knights',
        name: 'English: Four Knights',
        eco: 'A29',
        kind: 'line',
        side: 'white',
        summary: 'A reversed Sicilian with an extra tempo: fianchetto and pressure the long diagonal.',
        plan: 'Castle, then d3, a3 and b4 for a queenside expansion supported by the g2 bishop.',
        moves: [
          m('c4', 'Control d5 from the flank.'),
          m('e5', 'Black takes the center.'),
          m('Nc3', 'More control of d5.'),
          m('Nf6', 'Develop.'),
          m('Nf3', 'Pressure e5.'),
          m('Nc6', 'Defend.'),
          m('g3', 'Prepare the fianchetto.'),
          m('d5', 'Black grabs space.'),
          m('cxd5', 'Trade a flank pawn for a center pawn.'),
          m('Nxd5', 'Recapture.'),
          m('Bg2', 'The bishop hits d5 and the whole long diagonal.'),
          m('Nb6', 'Retreat to safety.'),
          m('O-O', 'Castle.'),
          m('Be7', 'Develop.'),
        ],
      },
      {
        id: 'reti-main',
        name: 'Réti Opening',
        eco: 'A13',
        kind: 'line',
        side: 'white',
        summary: 'Develop first, then undermine Black’s center with c4 and a double fianchetto.',
        plan: 'Bb2 and Bg2 aim at the center from afar; break with d4 or e4 once pieces are ready.',
        moves: [
          m('Nf3', 'Control the center with a piece and keep options open.'),
          m('d5', 'Black takes space.'),
          m('c4', 'Undermine d5.'),
          m('e6', 'Hold d5.'),
          m('g3', 'Fianchetto.'),
          m('Nf6', 'Develop.'),
          m('Bg2', 'The bishop hits d5.'),
          m('Be7', 'Develop.'),
          m('O-O', 'Castle.'),
          m('O-O', 'Castle.'),
          m('b3', 'Second fianchetto: Bb2 next.'),
        ],
      },
    ],
  },
]

export const ALL_LESSONS: OpeningLesson[] = FAMILIES.flatMap((family) => family.lessons)

export function lessonById(id: string): OpeningLesson | undefined {
  return ALL_LESSONS.find((lesson) => lesson.id === id)
}

export function familyOf(lessonId: string): OpeningFamily | undefined {
  return FAMILIES.find((family) => family.lessons.some((lesson) => lesson.id === lessonId))
}
